//PRINT ALL NUMBERS BETWEEN -10 AND 19
//PRINT ALLEVEN NUMBERS BETWEEN 10 AND 40
//PRINT ALL ODD NUMBERS BETWEEN 300 AND 333
//PRINT ALL NUMBERS DIVISIBLE BY 5 AND 3 BETWEEN 5 AND 50

var count = -10;
while (count < 20) {
    console.log("PRINT ALL NUMBERS BETWEEN -10 AND 19");
    count++;
}